server:
    port:${CUSTOM.SERVER.PORT:9080}
    
# Spring Cloud Gatewat Router
spring:
  cloud:
     gateway:
       routes:
         - id:product-service-route
         uri:lb://product-service
         predicates:
           - Path=/api/product-service/**
         filters:
           - StripPrefix=2
         
         
         - id:user-service-route
         uri:lb://user-service
         predicates:
           - Path=/api/user-service/**
         filters:
           - StripPrefix=2